<a href="https://github.com/sponsors/der-programmer1"
   target="_blank"
   rel="noopener noreferrer"
   aria-label="Sponsor support for der-programmer1"
   style="display:inline-flex;align-items:center;gap:10px;padding:8px 14px;border-radius:10px;
          background:linear-gradient(180deg,#ff8aa0,#ff5a7a);color:#fff;text-decoration:none;
          font-weight:600;box-shadow:0 6px 18px rgba(0,0,0,0.12);">
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
    <path d="M12 21s-7-4.5-9-8.5C0 7.5 4.03 4 7.5 4 9.75 4 12 5.5 12 5.5S14.25 4 16.5 4C19.97 4 24 7.5 21 12.5 19 16.5 12 21 12 21z"
          fill="white"/>
  </svg>
  Sponsor
</a>
